security:
    always_authenticate_before_granting: true
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: auto

    providers:
        #in_memory: { memory: ~ }
        database_users:
            entity: { class: App\Entity\User, property: username_canonical }

#        fos_userbundle:
#            id: fos_user.user_provider.username
#        backend_users:
#            memory:
#                users:
#                    test: { password: '$argon2i$v=19$m=1024,t=2,p=2$dUJPcHR2cjhlMzVidUlhRg$+CFhcNgXNnHylSCirj9MjEDO4ry0+3pSv3L1FGWNfms', roles: ['ROLE_ADMIN'] }
#        all_users:
#            chain:
#                providers: ['database_users', 'backend_users']

    role_hierarchy:
        ROLE_CUSTOM:      [ ROLE_USER ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        cms_admin:
            anonymous: ~
            context: cms
            pattern: ^/%cms.admin_path%
            form_login:
                check_path: /%cms.admin_path%/
                login_path: /%cms.admin_path%/
                default_target_path: /%cms.admin_path%/
            logout:
                path: /%cms.admin_path%/logout
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: REMEMBER_ME
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~
        main:
            anonymous: ~
            context: cms
            pattern: ^/
            form_login:
                # The route name that the login form submits to
                check_path: security_login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: security_login
                default_target_path: /
            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: cms_index
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: REMEMBER_ME
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/_assistant/, roles: ROLE_ADMIN }
        - { path: ^/%cms.admin_path%/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%cms.admin_path%/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%cms.admin_path%/system/config/, role: ROLE_ADMIN_CONFIG }
        - { path: ^/%cms.admin_path%, roles: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_FILEMANAGER }
        - { path: ^/elfinder, role: ROLE_FILEMANAGER }
#        - { path: ^/%user_path%/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%, roles: ROLE_USER }
