version: '3.7'
services:
    nginx:
        build:
            context: ./.docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php
        ports:
            - "${WEB_PORT}:80"
    php:
        build:
            context: ./.docker/development
            dockerfile: php74-fpm.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DATABASE_URL: 'pgsql://cms:1234@db:5432/cms?serverVersion=12.3'
#            DATABASE_URL: 'mysql://cms:1234@dbmysql:3306/cms?serverVersion=5.7'
#            DATABASE_URL: 'mysql://cms:1234@dbmysql:3306/cms?serverVersion=mariadb-10.3.20'
#        depends_on:
#            - dbmysql
    db:
        build:
            context: ./.docker/development
            dockerfile: postgres.docker
        restart: unless-stopped # always
        environment:
            POSTGRES_USER: cms
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: cms
        ports:
            - 54399:5432
        volumes:
            - cms-db:/var/lib/postgresql/data
#            - ./var/lib/postgresql/data:/var/lib/postgresql/data
#    dbmysql:
#        user: "1000:50"
#        build:
#            context: ./.docker/development
#            dockerfile: mariadb.docker
#        restart: always
#        environment:
#            MYSQL_DB: cms
#            MYSQL_USER: cms
#            MYSQL_PASSWORD: 1234
#            MYSQL_ROOT_PASSWORD: 1234
#        ports:
#            - 3366:3306
#        volumes:
#            - cms-db-mysql:/var/lib/mysql/data
##            - ./var/lib/mysql/data:/var/lib/mysql/data
#        command:
#            'mysqld --innodb-flush-method=fsync'

volumes:
    composer:
    cms-db:
    #cms-db-mysql:
