#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#smart_core_cms:
#    resource: '@CMSBundle/Resources/config/routing/routing.yml'
#    prefix: /

smart_core_cms:
    resource: '@CMSBundle/Resources/config/routes.yaml'
